src/components/offline/offline.tsx

This PR is about splitting the httpError text messages on the slate to 2 different cases 
If the browser is offline

fix: FEV-427 - improve errors message

---

src/decorator/live-decorator.ts

Current fix trigger _renderLiveTag method that handle proper state of live-tag

fix: update live-tag on pause (FEV-788)

---

src/decorator/live-decorator.ts
src/kaltura-live-plugin.tsx
src/middleware/live-middleware.ts

in decorator isLive method returns correct value for entry type

fix(FEV-758): Player v7 | Live 2.0.7| - Entry view - While the stream is in preview an error will be shown in the player

---

src/components/live-tag/live-tag.scss
src/components/live-tag/live-tag.tsx
src/kaltura-live-plugin.tsx

1) use player ui api to render live-tag component
2) simplify logic of live-tag state
3) refactored live-tag component to avoid unnecessary re-renders

fix(FEV-777):  Safari - Sometimes when the stream is restarted it will be played while showing the offline label

---

src/components/live-tag/live-tag.scss

FEV-787 - UI - there is not enough space between the 'Seek Forward' button and the 'Live' label

---

src/decorator/live-decorator.ts
src/kaltura-live-plugin.tsx

1) optimization: remove listener and handle 'timedmetadata' event in decorator
2) optimization: update live-tag on 'seeking' event like player.js does
3) prevent unnecessary re-render of custom live-tag

FEV-660 - Player V7| live 2.0.4| - Low network conditions - Live does not return to the correct time after low network conditions are removed

---

src/components/live-tag/live-tag.tsx
src/kaltura-live-plugin.tsx

set same condition for live-tag styles as player-ui live tag has

Player v7 | Live 2.1.1| - Sometimes, preview and live labels wrongly displayed as DVR (gray background color)

---

src/decorator/live-decorator.ts
src/kaltura-live-plugin.tsx

Decorator:
- changed way of decorator activation;
- reload media only after critical issues
Live plugin:
-  listeners for plugin and decorator activation moved on appropriate events
- unsubscribe from listeners

Player v7 | Live 2.1.2| IE11| Live entry failed to play when moving from preview to live

---

src/kaltura-live-plugin.tsx

1) use player API to attach and detach media (restore after end event handled);
2) use `player.Event.PLAYING` event to restore live edge after media got attached.

FEV-760 - Player V7| live 2.0.7| Edit WC page- VOD continues to be played on the player after moving from offline to preview

---

src/kaltura-live-plugin.tsx

1) for "live" entries without DVR display offline slate before "end" event dispatched;
2) prevent manually dispatching "end" event before media ended;

fix(FEV-1126): player is stuck on loading wheel and offline indicator appears when stopping the stream and DVR is disabled

---

src/decorator/live-decorator.ts

prevent get details call for non-live entry

fix(FEV-1128): Live slate is displayed for non-live entries when reaching the end of the video

---

src/decorator/live-decorator.ts
src/kaltura-live-plugin.tsx

display offline slate if error handled by live-decorator

fix(FEV-1135): offline slate doesn't appears for live media with DVR

---

src/kaltura-live-plugin.tsx

Once cue-point manager become push Kaltura cue-points to text-track API with type 'metadata' live-plugin trying to parse  Kaltura cue-points as a ID3 meta-tag.

fix(FEV-1144): JSON.parse method throws many errors during parsing ID3 tag

---

src/kaltura-live-plugin.tsx

this PR contains tuned values to improve the failover of primary/secondary and simulive to live (and live to simulive):
**_"maxStaleLevelReloads"_**
changed from 12 to 8 - as BE fixed to get informed about "dead" stream sooner than in the past - so we can reduce this value and get a better experience
**_"heartbeatTimeout"_**
conf of "native" reduced to improve failover in Safari browser. before this change - the value was 30 sec- and it caused 30 seconds of buffering in case of failover
**_"levelLoadingMaxRetryTimeout"_**
moved to the appropriate place (it was inside the "network" object and didn't affect)

fix(LIV-758): simulive to live and failovers confs tuning

---

src/kaltura-live-plugin.tsx

in case of DVR on - fast restart of the stream will cause dash playback to get stuck. this configuration should be added to shaka in order to solve it.
reference: https://github.com/google/shaka-player/issues/555#issuecomment-294552711

fix(LIV-905): fix mpeg-dash restart issues

---

src/decorator/live-decorator.ts
src/kaltura-live-plugin.tsx

proper handle stream status for simulive entry

fix(FEV-1403): When VOD source is shorter than the simulive window, the configured DVR will replay the last 10-15 seconds until page refresh is done

---

src/kaltura-live-plugin.tsx

change Kaltura-player network configuration (endlist manifest)

fix(FEV-1205): DVR play stops without reaching the end of the stream if the stream is stopped while the player is behind live edge

---

src/components/no-longer-live/no-longer-live.scss
src/components/offline/offline.scss
src/variables.scss

increase z-index for offline overlays

fix(FEV-1601): When a live stream with DVR OFF is stopped there is a spinner on top of the slate

---

README.md
src/kaltura-live-plugin.tsx

Solves: https://kaltura.atlassian.net/browse/FEC-13289
1) use buffering timeout to switch media between primary/secondary broadcast;
2) use `logger.debug` instead of `info`;

FEC-13289: V7 Failover is more than 35 seconds and Live failover delay affected by different plugins

---

src/kaltura-live-plugin.tsx

**Issue:**
When there is live entry in playlist, and the live entry is currently not broadcasting the playlist panel is closed after few seconds so user can't navigate in the playlist until the live will stream again.
**Fix:**
Do not deactivate the playlist panel when entry is offline
Solves [SUP-41353](https://kaltura.atlassian.net/browse/SUP-41353)
[SUP-41353]: https://kaltura.atlassian.net/browse/SUP-41353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-41353): Future live event in a playlist will remove the access to the side panel

---

README.md
cypress/e2e/kaltura-live.cy.ts
src/kaltura-live-plugin.tsx

set default value of `showLiveViewers` configuration to `false`.
[FEC-13353](https://kaltura.atlassian.net/browse/FEC-13353)
[FEC-13353]: https://kaltura.atlassian.net/browse/FEC-13353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13353): disable live viewers feature

---

cypress/e2e/kaltura-live.cy.ts
src/components/live-viewers/live-viewers-manager.tsx
src/components/live-viewers/live-viewers.tsx

- Rendering the live viewers number only when the number is different from 0.
- Only update live viewers count when the number is bigger than 0.
[FEC-14353](https://kaltura.atlassian.net/browse/FEC-14353)
[FEC-14353]: https://kaltura.atlassian.net/browse/FEC-14353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14353): When live viewers count equals to zero do not display viewers count

---

src/kaltura-live-plugin.tsx

**Description of the issue:**
`absolutePosition` is not being updated as expected which implies that the user haven’t watched the live video (even though they have).
**Technical explanation:**
- `VIEW` event is sent by kava plugin every 10 seconds
- in case of live playback, the kava dashboard is looking at `absolutePosition`, which represents the time when the view event was sent, in epoch
- the `absolutePosition` is taken from kaltura-live plugin; it is being calculated inside a callback function of a listener of `TIMED_METADATA` event
- in some cases (inconsistently), the `TIMED_METADATA` event is not being triggered (responsibility of engine video element)
- this is causing the issue where the `absolutePosition` is not being updated as expected
**Solution:**
assumption - …

fix(FEC-14441): live view analytic - fix absolutePosition
